# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

name: Bug Report
description: Report a bug or unexpected behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please add as much relevant information to the form below as you can.
        This will help us replicate and solve the issue. Thank you!
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Please describe the issue and the expected behavior.
      value: "[Expected behavior] and [actual behavior]."
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: System information
      description: Please run `scripts/info.sh` and paste the output here.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
