/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is @generated by gen_fwd.py
// Do not edit this file directly, instead update gen_fwd_input.toml and run:
// buck run @arvr/mode/platform010/opt //arvr/libraries/momentum:gen_fwd

#pragma once

#include <memory>

namespace momentum {

class ProgressBar;

using ProgressBar_p = ::std::shared_ptr<ProgressBar>;
using ProgressBar_u = ::std::unique_ptr<ProgressBar>;
using ProgressBar_w = ::std::weak_ptr<ProgressBar>;
using ProgressBar_const_p = ::std::shared_ptr<const ProgressBar>;
using ProgressBar_const_u = ::std::unique_ptr<const ProgressBar>;
using ProgressBar_const_w = ::std::weak_ptr<const ProgressBar>;

} // namespace momentum
