/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once

#if defined(MOMENTUM_WITH_XR_PROFILE)

#include <arvr/libraries/profile_redirect/annotate.hpp>

#define MT_PROFILE_FUNCTION() XR_PROFILE_FUNCTION()
#define MT_PROFILE_FUNCTION_CATEGORY(CATEGORY) XR_PROFILE_FUNCTION_CATEGORY(CATEGORY)
#define MT_PROFILE_EVENT(NAME) XR_PROFILE_EVENT(NAME)
#define MT_PROFILE_EVENT_DYNAMIC(NAME) XR_PROFILE_EVENT_DYNAMIC(NAME)
#define MT_PROFILE_CATEGORY(NAME, CATEGORY) XR_PROFILE_CATEGORY(NAME, CATEGORY)
#define MT_PROFILE_PREPARE_PUSH_POP() XR_PROFILE_PREPARE_PUSH_POP()
#define MT_PROFILE_PUSH(NAME) XR_PROFILE_PUSH(NAME)
#define MT_PROFILE_POP() XR_PROFILE_POP()
#define MT_PROFILE_THREAD(THREAD_NAME) XR_PROFILE_THREAD(THREAD_NAME)
#define MT_PROFILE_UPDATE() XR_PROFILE_UPDATE()
#define MT_PROFILE_BEGIN_FRAME() XR_PROFILE_BEGIN_FRAME()
#define MT_PROFILE_END_FRAME() XR_PROFILE_END_FRAME()
#define MT_PROFILE_METADATA(NAME, DATA) XR_PROFILE_METADATA(NAME, DATA)

#else

#define MT_PROFILE_FUNCTION()
#define MT_PROFILE_FUNCTION_CATEGORY(CATEGORY)
#define MT_PROFILE_EVENT(NAME)
#define MT_PROFILE_EVENT_DYNAMIC(NAME)
#define MT_PROFILE_CATEGORY(NAME, CATEGORY)
#define MT_PROFILE_PREPARE_PUSH_POP()
#define MT_PROFILE_PUSH(NAME)
#define MT_PROFILE_POP()
#define MT_PROFILE_THREAD(THREAD_NAME)
#define MT_PROFILE_UPDATE()
#define MT_PROFILE_BEGIN_FRAME()
#define MT_PROFILE_END_FRAME()
#define MT_PROFILE_METADATA(NAME, DATA)

#endif
