name: CI macOS

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/website/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/website/**"

jobs:
  momentum:
    name: cpp-${{ matrix.mode == '' && 'opt' || 'dev' }}-${{ matrix.os == 'macos-latest-large' && 'mac-x86_64' || 'mac-arm64' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-latest-large]
        mode: ["", "_dev"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FBX SDK
        run: |
          curl -O https://damassets.autodesk.net/content/dam/autodesk/www/files/fbx202037_fbxsdk_clang_mac.pkg.tgz
          tar -xvf fbx202037_fbxsdk_clang_mac.pkg.tgz
          sudo installer -pkg fbx202037_fbxsdk_clang_macos.pkg -target /

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          cache: true

      - name: Build and test Momentum
        run: |
          MOMENTUM_BUILD_IO_FBX=ON \
            pixi run test${{ matrix.mode }}

      - name: Install Momentum and Build hello_world
        run: |
          pixi run install
          pixi run cmake \
            -S momentum/examples/hello_world \
            -B momentum/examples/hello_world/build \
            -DCMAKE_BUILD_TYPE=Release
          pixi run cmake --build momentum/examples/hello_world/build

  pymomentum:
    name: py-${{ matrix.os == 'macos-latest-large' && 'mac-x86_64' || 'mac-arm64' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-latest-large]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FBX SDK
        run: |
          curl -O https://damassets.autodesk.net/content/dam/autodesk/www/files/fbx202037_fbxsdk_clang_mac.pkg.tgz
          tar -xvf fbx202037_fbxsdk_clang_mac.pkg.tgz
          sudo installer -pkg fbx202037_fbxsdk_clang_macos.pkg -target /

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          cache: true

      - name: Build and test PyMomentum
        run: |
          MOMENTUM_BUILD_IO_FBX=ON \
            pixi run test_py

      - name: Build Python API Doc
        run: |
          MOMENTUM_BUILD_IO_FBX=ON \
            pixi run doc_py
