name: CI macOS

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/website/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/website/**"

jobs:
  momentum:
    name: momentum-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: mac-arm
          - os: macos-latest-large
            platform: mac-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
      - name: Build and test Momentum
        run: |
          pixi run test
      - name: Install Momentum and Build hello_world
        run: |
          pixi run install
          pixi run cmake \
            -S momentum/examples/hello_world \
            -B momentum/examples/hello_world/build \
            -DCMAKE_BUILD_TYPE=Release
          pixi run cmake --build momentum/examples/hello_world/build

  pymomentum:
    name: pymomentum-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: mac-arm
          - os: macos-latest-large
            platform: mac-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
      - name: Build PyMomentum
        # TODO: Change to test_pymomentum once segfault on import is fixed
        run: |
          pixi run build_pymomentum
