name: CI Windows

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/website/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/website/**"

jobs:
  build:
    name: cpp-${{ matrix.mode == '' && 'opt' || 'dev' }}-win
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [""]  # TODO: Add -dev model
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          cache: true

      - name: Build and test Momentum
        run: |
          pixi run test${{ matrix.mode }}

      - name: Install Momentum and Build hello_world
        run: |
          pixi run install
          pixi run cmake `
            -S momentum/examples/hello_world `
            -B momentum/examples/hello_world/build
          pixi run cmake `
            --build momentum/examples/hello_world/build `
            --config Release `
            --parallel
